env:
  es6: true
  browser: true
  commonjs: true
  jest: true

plugins: ['react', 'prettier']

extends: [ 'plugin:prettier/recommended', 'prettier/react', 'prettier/standard']

rules: 
  prettier/prettier: error

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

settings:
  react:
    version: '16'
